steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', '-t',
      'us-central1-docker.pkg.dev/semester-2-408906/rohith-100936904/assignment2:${COMMIT_SHA}',
      '.'
    ]

  # Step 2: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'us-central1-docker.pkg.dev/semester-2-408906/rohith-100936904/assignment2:${COMMIT_SHA}'
    ]

  # Step 3: Deploy the application to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      gcloud run deploy assignment2 \
        --image us-central1-docker.pkg.dev/semester-2-408906/rohith-100936904/assignment2:${COMMIT_SHA} \
        --region=us-central1 \
        --port=8080 \
        --platform=managed \
        --allow-unauthenticated

images:
  - 'us-central1-docker.pkg.dev/semester-2-408906/rohith-100936904/assignment2:${COMMIT_SHA}'

options:
  logging: CLOUD_LOGGING_ONLY
